export interface PDFFormData {
  fullName: string;
  email: string;
  phone: string;
  monthlyEarnings: string;
  specialization: string;
  yearsExperience: string;
  clientCountries: string;
  preferredBank: string;
  tinNumber: string;
}

const bankInfo: Record<string, { phone: string; email: string; branch: string }> = {
  "Dashen Bank": {
    phone: "+251 115 523 048",
    email: "info@dashenbanksc.com",
    branch: "Dashen Bank, Churchill Road Branch, Addis Ababa",
  },
  "Awash Bank": {
    phone: "+251 115 501 862",
    email: "info@awash-international.com",
    branch: "Awash Bank, Main Branch, Addis Ababa",
  },
  "Bank of Abyssinia": {
    phone: "+251 115 501 110",
    email: "info@bankofabyssinia.com",
    branch: "Bank of Abyssinia, Head Office, Addis Ababa",
  },
  "Commercial Bank of Ethiopia": {
    phone: "+251 115 514 300",
    email: "info@combanketh.et",
    branch: "Commercial Bank of Ethiopia, Addis Ababa",
  },
  Other: {
    phone: "Contact your local bank",
    email: "Contact your local bank",
    branch: "Your preferred bank branch, Addis Ababa",
  },
};

export async function generatePDF(data: PDFFormData): Promise<void> {
  const { default: jsPDF } = await import("jspdf");
  const { default: autoTable } = await import("jspdf-autotable");

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentW = pageW - margin * 2;
  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const bank = bankInfo[data.preferredBank] || bankInfo["Other"];

  const addHeader = (pageNum: number, title: string) => {
    // Ethiopian flag stripe
    doc.setFillColor(0, 150, 57); // green
    doc.rect(0, 0, pageW / 3, 8, "F");
    doc.setFillColor(252, 221, 9); // gold
    doc.rect(pageW / 3, 0, pageW / 3, 8, "F");
    doc.setFillColor(218, 18, 26); // red
    doc.rect((pageW * 2) / 3, 0, pageW / 3, 8, "F");

    // Logo text
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 150, 57);
    doc.text("Netsalancer", margin, 20);

    // Tagline
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 100, 100);
    doc.text("Your earnings. Your currency. Your freedom.", margin, 26);

    // Directive badge
    doc.setFillColor(0, 150, 57);
    doc.roundedRect(pageW - margin - 50, 12, 50, 10, 3, 3, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.text("FXD/04/2026", pageW - margin - 25, 18, { align: "center" });

    // Title
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(26, 26, 26);
    doc.text(title, margin, 38);

    // Divider
    doc.setDrawColor(0, 150, 57);
    doc.setLineWidth(0.5);
    doc.line(margin, 41, pageW - margin, 41);

    return 48; // return starting y position for content
  };

  const addFooter = (pageNum: number, totalPages: number) => {
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${pageNum} of ${totalPages} | Generated by Netsalancer | mikimuluw@gmail.com | netsalancer.et`,
      pageW / 2,
      pageH - 8,
      { align: "center" }
    );

    // Bottom flag stripe
    doc.setFillColor(0, 150, 57);
    doc.rect(0, pageH - 4, pageW / 3, 4, "F");
    doc.setFillColor(252, 221, 9);
    doc.rect(pageW / 3, pageH - 4, pageW / 3, 4, "F");
    doc.setFillColor(218, 18, 26);
    doc.rect((pageW * 2) / 3, pageH - 4, pageW / 3, 4, "F");
  };

  // =============================================
  // PAGE 1: Cover Letter
  // =============================================
  let y = addHeader(1, "Bank Application Cover Letter");

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(60, 60, 60);

  // Date
  doc.text(today, margin, y);
  y += 10;

  // Recipient
  doc.setFont("helvetica", "bold");
  doc.text(data.preferredBank, margin, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.text("Foreign Exchange Department", margin, y);
  y += 5;
  doc.text(bank.branch, margin, y);
  y += 10;

  // Subject
  doc.setFont("helvetica", "bold");
  doc.text(
    "Subject: Application for Foreign Currency (FX) Retention Account under FXD/04/2026",
    margin,
    y,
    { maxWidth: contentW }
  );
  y += 10;

  doc.setFont("helvetica", "normal");
  doc.text("Dear Sir/Madam,", margin, y);
  y += 8;

  // Body paragraphs
  const para1 = `I am writing to apply for a Foreign Currency Retention Account as permitted under Foreign Exchange Directive No. FXD/04/2026, Sub-article 6.2, which states:`;
  const splitPara1 = doc.splitTextToSize(para1, contentW);
  doc.text(splitPara1, margin, y);
  y += splitPara1.length * 5 + 4;

  // Quote box
  doc.setFillColor(240, 249, 244);
  doc.setDrawColor(0, 150, 57);
  doc.setLineWidth(0.3);
  const quoteText = `"Any service exporter is entitled to hold 100 percent of its export proceeds in an FX retention account for an indefinite period."`;
  const splitQuote = doc.splitTextToSize(quoteText, contentW - 12);
  const quoteH = splitQuote.length * 5 + 8;
  doc.roundedRect(margin, y - 2, contentW, quoteH, 2, 2, "FD");
  doc.setFont("helvetica", "italic");
  doc.setTextColor(0, 100, 50);
  doc.text(splitQuote, margin + 6, y + 4);
  y += quoteH + 6;

  // Personal info box
  doc.setFillColor(248, 249, 250);
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.3);

  const personalData = [
    ["Full Name:", data.fullName],
    ["Phone:", data.phone],
    ["Email:", data.email],
    ["Specialization:", data.specialization],
    ["Years of Experience:", data.yearsExperience + " years"],
    ...(data.tinNumber ? [["TIN Number:", data.tinNumber]] : []),
  ];

  doc.setFont("helvetica", "bold");
  doc.setTextColor(26, 26, 26);
  doc.text("Personal Information:", margin, y);
  y += 6;

  personalData.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.setTextColor(80, 80, 80);
    doc.setFontSize(9);
    doc.text(label, margin + 2, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(30, 30, 30);
    doc.text(value, margin + 45, y);
    y += 5;
  });
  y += 4;

  // Nature of service
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(26, 26, 26);
  doc.text("Nature of Service Export:", margin, y);
  y += 6;

  const para2 = `I provide ${data.specialization} services to international clients primarily located in ${data.clientCountries}. My services generate foreign exchange earnings of approximately $${data.monthlyEarnings} per month through digital service exports.`;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(60, 60, 60);
  const splitPara2 = doc.splitTextToSize(para2, contentW);
  doc.text(splitPara2, margin, y);
  y += splitPara2.length * 5 + 6;

  // Documentation
  doc.setFont("helvetica", "bold");
  doc.setTextColor(26, 26, 26);
  doc.text("Supporting Documentation:", margin, y);
  y += 6;

  const docs = [
    "Copy of National ID / Passport",
    "TIN Certificate" + (data.tinNumber ? ` (TIN: ${data.tinNumber})` : " (if available)"),
    "Contracts / Invoices with foreign clients",
    "Bank statements showing previous FX receipts",
    "Business / Trade license (if applicable)",
  ];

  doc.setFont("helvetica", "normal");
  doc.setTextColor(60, 60, 60);
  docs.forEach((d) => {
    doc.text("• " + d, margin + 4, y);
    y += 5;
  });
  y += 6;

  const closing = "I look forward to opening this account and contributing to Ethiopia's foreign exchange earnings through formal banking channels.";
  const splitClosing = doc.splitTextToSize(closing, contentW);
  doc.text(splitClosing, margin, y);
  y += splitClosing.length * 5 + 6;

  doc.text("Sincerely,", margin, y);
  y += 8;
  doc.setFont("helvetica", "bold");
  doc.setTextColor(26, 26, 26);
  doc.text(data.fullName, margin, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text(data.phone, margin, y);
  y += 5;
  doc.text(data.email, margin, y);

  addFooter(1, 5);

  // =============================================
  // PAGE 2: FXD/04/2026 Key Provisions
  // =============================================
  doc.addPage();
  y = addHeader(2, "FXD/04/2026 — Key Provisions Summary");

  const provisions = [
    {
      title: "Article 6.2 — 100% FX Retention",
      text: "Any service exporter is entitled to hold 100 percent of its export proceeds in an FX retention account for an indefinite period. This means you can keep all your USD earnings in a bank account permanently — no forced conversion.",
    },
    {
      title: "Service Exporter Definition",
      text: "A 'service exporter' includes individuals and entities providing digital services, IT, consulting, creative services, and other professional services to international clients. Ethiopian freelancers on platforms like Upwork, Toptal, Fiverr, and direct client contracts qualify.",
    },
    {
      title: "International Card Issuance",
      text: "Banks are authorized to issue international Visa or Mastercard cards linked to FX retention accounts. This allows direct international spending — for tools, subscriptions, shopping, and services — without conversion.",
    },
    {
      title: "No Minimum Deposit Requirement",
      text: "FXD/04/2026 removes all minimum deposit requirements for FX retention accounts. Any freelancer, regardless of earnings level, can open and maintain an account.",
    },
    {
      title: "Legal Protection & Compliance",
      text: "Operating through formal FX channels under FXD/04/2026 provides full legal protection. Account freeze risk is eliminated. All transactions are NBE-compliant and fully documented.",
    },
    {
      title: "Effective Date",
      text: "FXD/04/2026 became effective February 12, 2026. All qualifying service exporters may apply for FX retention accounts immediately at participating banks.",
    },
  ];

  provisions.forEach((p) => {
    if (y > pageH - 50) {
      doc.addPage();
      y = addHeader(2, "FXD/04/2026 — Key Provisions (continued)");
      addFooter(2, 5);
    }

    doc.setFillColor(0, 150, 57, 0.1);
    doc.setFillColor(240, 249, 244);
    doc.setDrawColor(0, 150, 57);
    doc.setLineWidth(0.3);

    const titleLines = doc.splitTextToSize(p.title, contentW - 10);
    const textLines = doc.splitTextToSize(p.text, contentW - 10);
    const boxH = (titleLines.length + textLines.length) * 5 + 12;

    if (y + boxH > pageH - 30) {
      doc.addPage();
      y = addHeader(2, "FXD/04/2026 — Key Provisions (continued)");
      addFooter(2, 5);
    }

    doc.roundedRect(margin, y - 2, contentW, boxH, 2, 2, "D");
    doc.setFillColor(0, 150, 57);
    doc.roundedRect(margin, y - 2, 3, boxH, 1, 1, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(0, 100, 50);
    doc.text(titleLines, margin + 6, y + 4);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    doc.text(textLines, margin + 6, y + 4 + titleLines.length * 5 + 2);

    y += boxH + 6;
  });

  addFooter(2, 5);

  // =============================================
  // PAGE 3: Documentation Checklist
  // =============================================
  doc.addPage();
  y = addHeader(3, "Documentation Checklist");

  const checklistItems = [
    {
      category: "Identity Documents",
      items: [
        "National ID or Passport (photocopy, front and back)",
        "Recent passport-size photograph",
      ],
    },
    {
      category: "Tax & Business Documents",
      items: [
        "TIN Certificate (if registered)" + (data.tinNumber ? ` — Your TIN: ${data.tinNumber}` : ""),
        "Business / Trade License (if applicable)",
        "Trade Name Registration (if applicable)",
      ],
    },
    {
      category: "Proof of Service Export",
      items: [
        "Sample contracts with international clients (min. 2)",
        "Invoices showing foreign client payments (last 3-6 months)",
        "Portfolio or work samples demonstrating service type",
        "Client testimonials or references (optional but helpful)",
        "Screenshots / proof of online freelance profiles",
      ],
    },
    {
      category: "Financial Documents",
      items: [
        "Bank statements (last 3-6 months if available)",
        "Payoneer / PayPal / Wise transaction history (optional)",
        "Any previous FX receipts or transfer records",
      ],
    },
    {
      category: "Bank-Specific Requirements",
      items: [
        `Completed account opening form from ${data.preferredBank}`,
        `Initial deposit (no minimum required under FXD/04/2026)`,
        "KYC (Know Your Customer) information form",
        "Source of funds declaration",
      ],
    },
  ];

  checklistItems.forEach((section) => {
    if (y > pageH - 60) {
      doc.addPage();
      y = addHeader(3, "Documentation Checklist (continued)");
      addFooter(3, 5);
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(0, 100, 50);
    doc.text(section.category, margin, y);
    y += 6;

    section.items.forEach((item) => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(60, 60, 60);

      // Checkbox
      doc.setDrawColor(100, 100, 100);
      doc.setLineWidth(0.3);
      doc.rect(margin + 2, y - 3.5, 4, 4, "D");

      const itemLines = doc.splitTextToSize(item, contentW - 14);
      doc.text(itemLines, margin + 8, y);
      y += itemLines.length * 4.5 + 2;
    });

    y += 4;
  });

  addFooter(3, 5);

  // =============================================
  // PAGE 4: Timeline & Next Steps
  // =============================================
  doc.addPage();
  y = addHeader(4, "Implementation Timeline & Next Steps");

  const steps = [
    {
      week: "Week 1",
      title: "Submit Application",
      details: [
        `Visit ${data.preferredBank} main branch, Foreign Exchange Department`,
        "Bring all documents from the checklist (Page 3)",
        "Request specifically: FX Retention Account under FXD/04/2026",
        `Bank contact: ${bank.phone}`,
      ],
    },
    {
      week: "Week 2",
      title: "KYC Verification",
      details: [
        "Bank reviews your application and documentation",
        "KYC (Know Your Customer) verification process",
        "You may be contacted for additional information",
        "Follow up if you don't hear back within 5 business days",
      ],
    },
    {
      week: "Week 3",
      title: "Account Approval & Opening",
      details: [
        "Account approval and formal opening",
        "Receive account number and banking credentials",
        "Set up online banking access",
        "Notify your international clients of new banking details",
      ],
    },
    {
      week: "Week 4",
      title: "International Card Application",
      details: [
        "Apply for international Visa/Mastercard linked to FX account",
        "Provide additional KYC information if required",
        "Card production typically takes 2-4 weeks",
        "Set up card controls and spending limits",
      ],
    },
    {
      week: "Week 6-8",
      title: "Full FX Freedom",
      details: [
        "Receive physical international card",
        "Start receiving payments directly to FX account",
        "Begin accumulating bank statements for visa applications",
        "Access all international digital services and platforms",
      ],
    },
  ];

  steps.forEach((step, i) => {
    if (y > pageH - 70) {
      doc.addPage();
      y = addHeader(4, "Timeline & Next Steps (continued)");
      addFooter(4, 5);
    }

    // Step box
    doc.setFillColor(i === 0 ? 0 : 248, i === 0 ? 150 : 249, i === 0 ? 57 : 250);
    doc.setDrawColor(i === 0 ? 0 : 220, i === 0 ? 150 : 220, i === 0 ? 57 : 220);
    doc.setLineWidth(0.3);

    const detailLines = step.details.map((d) =>
      doc.splitTextToSize("• " + d, contentW - 20)
    );
    const totalDetailLines = detailLines.reduce(
      (sum, lines) => sum + lines.length,
      0
    );
    const boxH = totalDetailLines * 4.5 + 20;

    doc.roundedRect(margin, y - 2, contentW, boxH, 3, 3, "D");

    // Week badge
    doc.setFillColor(i === 0 ? 0 : 100, i === 0 ? 150 : 100, i === 0 ? 57 : 100);
    doc.roundedRect(margin + 4, y + 1, 18, 7, 2, 2, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);
    doc.setTextColor(255, 255, 255);
    doc.text(step.week, margin + 13, y + 6, { align: "center" });

    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(26, 26, 26);
    doc.text(step.title, margin + 26, y + 6);

    let detailY = y + 14;
    detailLines.forEach((lines) => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(80, 80, 80);
      doc.text(lines, margin + 8, detailY);
      detailY += lines.length * 4.5;
    });

    y += boxH + 5;
  });

  // Bank contact box
  if (y > pageH - 50) {
    doc.addPage();
    y = addHeader(4, "Contact Information");
    addFooter(4, 5);
  }

  doc.setFillColor(240, 249, 244);
  doc.setDrawColor(0, 150, 57);
  doc.setLineWidth(0.5);
  doc.roundedRect(margin, y, contentW, 35, 3, 3, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(0, 100, 50);
  doc.text(`${data.preferredBank} — FX Department`, margin + 5, y + 8);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  doc.text(`📞 ${bank.phone}`, margin + 5, y + 15);
  doc.text(`📧 ${bank.email}`, margin + 5, y + 21);
  doc.text(`📍 ${bank.branch}`, margin + 5, y + 27);

  y += 42;

  doc.setFillColor(248, 249, 250);
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.roundedRect(margin, y, contentW, 22, 3, 3, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(0, 150, 57);
  doc.text("Questions? Contact Netsalancer:", margin + 5, y + 8);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(60, 60, 60);
  doc.setFontSize(9);
  doc.text("📧 mikimuluw@gmail.com  |  🌐 netsalancer.et", margin + 5, y + 15);

  addFooter(4, 5);

  // =============================================
  // PAGE 5: Earnings Projection Worksheet
  // =============================================
  doc.addPage();
  y = addHeader(5, "Earnings Projection Worksheet");

  const monthly = parseFloat(data.monthlyEarnings) || 0;
  const annual = monthly * 12;
  const etbRate = 155;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  doc.text(
    `Prepared for: ${data.fullName}  |  Specialization: ${data.specialization}`,
    margin,
    y
  );
  y += 8;

  // Summary boxes
  const summaryData = [
    {
      label: "Monthly USD Earnings",
      value: `$${monthly.toLocaleString()}`,
      sub: "Per month",
    },
    {
      label: "Annual USD Earnings",
      value: `$${annual.toLocaleString()}`,
      sub: "Per year",
    },
    {
      label: "Annual ETB Value",
      value: `${(annual * etbRate).toLocaleString()} ETB`,
      sub: "@ 155 ETB/USD",
    },
  ];

  const boxW = (contentW - 8) / 3;
  summaryData.forEach((box, i) => {
    const bx = margin + i * (boxW + 4);
    doc.setFillColor(240, 249, 244);
    doc.setDrawColor(0, 150, 57);
    doc.setLineWidth(0.3);
    doc.roundedRect(bx, y, boxW, 22, 2, 2, "FD");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(0, 100, 50);
    doc.text(box.value, bx + boxW / 2, y + 10, { align: "center" });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(100, 100, 100);
    doc.text(box.label, bx + boxW / 2, y + 16, { align: "center" });
    doc.text(box.sub, bx + boxW / 2, y + 20, { align: "center" });
  });
  y += 30;

  // Monthly tracking table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(26, 26, 26);
  doc.text("Monthly FX Receipt Tracker", margin, y);
  y += 6;

  autoTable(doc, {
    startY: y,
    head: [["Month", "Client Name", "Service", "USD Amount", "Receipt/Invoice #", "Notes"]],
    body: Array.from({ length: 12 }, (_, i) => {
      const date = new Date(2026, i);
      const monthName = date.toLocaleString("en-US", { month: "long", year: "numeric" });
      return [monthName, "", "", "$", "", ""];
    }),
    styles: {
      fontSize: 8,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: [0, 150, 57],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [248, 249, 250],
    },
    columnStyles: {
      0: { cellWidth: 28 },
      3: { cellWidth: 20 },
      4: { cellWidth: 28 },
    },
    margin: { left: margin, right: margin },
  });

  addFooter(5, 5);

  // Save the PDF
  const safeName = data.fullName.replace(/[^a-zA-Z0-9]/g, "_");
  const dateStr = new Date().toISOString().split("T")[0];
  doc.save(`Netsalancer_FX_Freedom_Package_${safeName}_${dateStr}.pdf`);
}
